function [sMCoeffsN, ...
          sM0, ...
          PolynomialBasisCoeffsN, ...
          sMonomialBasisN, ...
          sMonomialBasis0, ...
           ParamsN_bnd   , ...
          sParamsN       , ...
          sParamsNOfParams, ...
          sParamsOfParamsN] = rewriteInNormalizedCoeffsAndMonomialBasis(sMCoeffs, ...
                                                                        sMonomialBasis, ...
                                                                        sParams, ...
                                                                        params_bnd, ...
                                                                        params_Offset, ...
                                                                        params_Amplitude, ...
                                                                        newParamName)

[PolynomialBasisCoeffsN, ...
        sMonomialBasisN, ...
        sMonomialBasis0, ...
         ParamsN_bnd   , ...
        sParamsN       , ...
        sParamsNOfParams, ...
        sParamsOfParamsN] = normalizeMonomialBasis(sMonomialBasis   , ...
                                                   sParams          , ...
                                                   params_bnd       , ...
                                                   params_Offset    , ...
                                                   params_Amplitude , ...
                                                   newParamName);

% Generate the fat coefficient matrix mapping the new monomial basis to the
% old monomial basis
PolynomialBasisCoeffsN_mat = writeFatMatrixFromCoeffCells(PolynomialBasisCoeffsN);

% Generate the fat coefficient matrix for the new monomial basis
sMCoeffs_mat   = writeFatMatrixFromCoeffCells(sMCoeffs);
if isempty(sMCoeffs)
    na = 0;
else
    na = size(sMCoeffs{1}, 2);
end
sMCoeffsN_mat  = sMCoeffs_mat*kron(PolynomialBasisCoeffsN_mat, I(na));

% Generate cell array of coefficient matrices for the new monomial basis
sMCoeffsN = writeCoeffCellsFromFatMatrix(sMCoeffsN_mat, sMonomialBasisN, na);

% Shift the nominal offset to the nominal system matrices
sM0                    = sMCoeffs_mat*kron(sMonomialBasis0, I(na));